### ISSUE TITLE
Can't follow example code if I install via Pod

### ISSUE THREAD

**Issue by huydangquoc** [hemangshah/HHFloatingView#1]
As I follow [Installation](https://github.com/hemangshah/HHFloatingView#installation) section

If I install **manually** and follow [example](https://github.com/hemangshah/HHFloatingView/tree/master/HHFloatingView/Example) project, It works well.

If I install via **cocoa pod** and follow the same [example](https://github.com/hemangshah/HHFloatingView/tree/master/HHFloatingView/Example) project, I get this error
<img width="873" alt="internal access level" src="https://user-images.githubusercontent.com/18465465/46339753-d570d580-c65d-11e8-94c4-df8a6c0da67e.png">

When I change access level of **reload** and **close** functions to public, it works well.
<img width="628" alt="change to public" src="https://user-images.githubusercontent.com/18465465/46339847-09e49180-c65e-11e8-8159-7c6c0efc3513.png">

@hemangshah 
Please help consider change these methods accordingly. Or if you're OK with these changes, I will create PR for them.

Thanks,
Huy

**Comment by hemangshah** [comment]
@huydangquoc , thank you! I am surprised there are 78 downloads made via CocoaPods and you only complaint about it 👍 I'll release a new version soon. Will keep you posted. I would love to have your PR but I need to make some more changes (refactoring) of code to have best swift practices so this time I'll handle this. But feel free to give your feedback on the same.

**Comment by hemangshah** [comment]
Hi again @huydangquoc , 

 🚀  HHFloatingView (1.4.0) successfully published
 📅  October 2nd, 18:56
 🌎  https://cocoapods.org/pods/HHFloatingView

Please feel free to use the latest pod and give your feedback.

**Comment by huydangquoc** [comment]
Dear @hemangshah, thank you for your quick response, highly appreciate it.
