### ISSUE TITLE
点击handlerButton没有回调吗？

### ISSUE THREAD

**Issue by biostome** [hemangshah/HHFloatingView#6]

**Comment by hemangshah** [comment]
Hi @biostome, I don't know Chinese language so used Google Translator to understand what you're trying to say: "You're looking for a touch (tap) event/action call back for the handler button, right?".

**Comment by biostome** [comment]
对～你对翻译正确。
我想知道点击 handler button 的回调在哪里

**Comment by biostome** [comment]
> Hi @biostome, I don't know Chinese language so used Google Translator to understand what you're trying to say: "You're looking for a touch (tap) event/action call back for the handler button, right?".
对～你对翻译正确。
我想知道点击 handler button 的回调在哪里

**Comment by biostome** [comment]
@hemangshah 对～你对翻译正确。
我想知道点击 handler button 的回调在哪里

**Comment by hemangshah** [comment]
Sorry for the late reply, right now that option isn't implemented but if you're not in a rush I can provide you a fix in a week or so. For now, to know this you can use this delegates to know when the handle button is tapped and options are visible or not.

You can implement below delegates to know this.

```
func floatingView(floatingView: HHFloatingView, willShowOption index: Int) {
   if index  == 0 { //... handler button is tapped for showing the options ... )
}

func floatingView(floatingView: HHFloatingView, willHideOption index: Int) {
   if index  == 0 { //... handler button is tapped for hiding the options ... )
}

```

**Comment by hemangshah** [comment]
Hi @biostome , I've added this delegate to know if we're opening/closing the `HHFloatingView`. Hope this will help.

Implement -

    func floatingView(floatingView: HHFloatingView, didTapHandler isOpening: Bool) {
        if isOpening {
            print("To open")
        } else {
            print("To close")
        }
    }
